language: node_js
services: mongodb
git:
  submodules: false
node_js:
- '8.6.0'
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &1
    repo: alexpelan/hornung
  bucket: hornung-production
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: hornung-production
  key: latest.zip
  bundle_type: zip
  application: hornung
  deployment_group: hornung
  region: us-west-2
  on: *1
  wait-until-deployed: true
script:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
before_install:
- openssl aes-256-cbc -K $encrypted_289b961959b9_key -iv $encrypted_289b961959b9_iv
  -in env.production.enc -out env.production -d
